# Generated by Django 4.0.5 on 2022-08-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
