# Generated by Django 4.0.5 on 2022-08-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0006_alter_application_client_secret'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('courses', '0005_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_permission',
        ),
    ]
